on:
    repository_dispatch:
    release:
           types: [published, created, prereleased]
jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-18.04, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        env:
            CURRENT_GITHUB_REF: ${{ github.event.client_payload.ref || github.ref }}
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ env.CURRENT_GITHUB_REF }}
            - uses: actions/setup-node@master
              with:
                  node-version: '13.x'
            - name: Install deps
              run: npm install
              env:
                  SKIP_BUILD: 1
            - name: Change version if master
              if: contains(env.CURRENT_GITHUB_REF, '0.0.0-latest-master')
              run: npm --no-git-tag-version version 0.0.0-latest-master
            - name: Prebuild binary
              run: npm run prebuild:build
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: prebuilds/@nodegui/*.tar.gz
                  tag_name: ${{ env.CURRENT_GITHUB_REF }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
